apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: myapp-backend
  template:
    metadata:
      labels:
        app: myapp-backend
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: "myapp-redis"
            - name: REDIS_PORT
              value: "6379"
          resources:
{{ toYaml .Values.backend.resources | indent 12 }}
